version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: money_manager_postgres
    environment:
      POSTGRES_USER: money_manager_web_user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: money_manager_web_db
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  moneymanager.api:
    image: moneymanager.api
    build:
      context: .
      dockerfile: Presentation/MoneyManager.API/Dockerfile
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - moneymanager.api
    restart: always

volumes:
  pgdata:
