version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: money_manager_postgres
    environment:
      POSTGRES_USER: money_manager_web_user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: money_manager_web_db
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  moneymanager.api:
    image: moneymanager.api
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: Presentation/MoneyManager.API/Dockerfile
    depends_on:
      - postgres

volumes:
  pgdata:
