using MediatR;

namespace MoneyManager.Application.Features.CQRS.Queries.Product.GetAllProductWithoutPagination;

public class GetAllProductWithoutPaginationQueryRequest: IRequest<List<GetAllProductWithoutPaginationQueryResponse>>;